### PR TITLE
Image and form input

### LINKED ISSUE #6: Input component
### Input component
- [ ] Basic text input
- [ ] Input with error validation
- [ ] Input with success validation
- [ ] Disabled input

### LINKED ISSUE #8: Image component
### Image component
- [ ] Responsive image
- [ ] Round image

### PR DESCRIPTION
**Pull request by siddhigate**
Image component
- Responsive image
- Round image

Form Input component
- Basic input
- Required input
- Validation
- Disabled input

**Preview:** https://upsleek-css-component-library-git-image-and-input-siddhigate.vercel.app/

### CODE REVIEW

**Review by adidoshi — APPROVED** [review]
Hey, look's great, form.css code is well structured. Also, I was curious are you working with issues with this project.... it looks well managed👍

**Review by manojasarsa — APPROVED** [review]
Looks good and well structured.

**Comment by siddhigate** [comment]
> Hey, look's great, form.css code is well structured. Also, I was curious are you working with issues with this project.... it looks well managed👍

Yes I'm working with issues with this project. Thanks for your feedback!

**Comment by adidoshi** [comment]
> > Hey, look's great, form.css code is well structured. Also, I was curious are you working with issues with this project.... it looks well managed👍
> 
> Yes I'm working with issues with this project. Thanks for your feedback!

Cool! Excited to know more about issues, it would be great if you explain how you worked with this...some time if possible😊!

**Comment by siddhigate** [comment]
> > > Hey, look's great, form.css code is well structured. Also, I was curious are you working with issues with this project.... it looks well managed👍
> > 
> > 
> > Yes I'm working with issues with this project. Thanks for your feedback!
> 
> Cool! Excited to know more about issues, it would be great if you explain how you worked with this...some time if possible😊!

Yes sure! Let's have a meet on VC today eve. Ping me on discord whenever u r free.

**Pull request merged**
